language: r
cache:
  - ccache
latex: false
dist: trusty
sudo: required

addons:
  apt:
    packages:
     - ccache

before_install:
  #- mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository ppa:opencpu/jq --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libv8-dev
  - sudo apt-get install --yes libjq-dev libprotobuf-dev libprotoc-dev protobuf-compiler r-cran-ncdf4
  #- sudo apt-get install r-data.table

r_packages:
  - devtools
warnings_are_errors: false

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

